IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'H_DW')
DROP TABLE dbo.H_DW 
GO
TRUNCATE TABLE D_ElementoParque
TRUNCATE TABLE D_Ingreso
TRUNCATE TABLE D_Gasto
TRUNCATE TABLE D_Tiempo